### ISSUE TITLE
User overview transactions do not seem to be linked to the selected user

### ISSUE THREAD

**Issue by JustSamuel** [GEWIS/sudosos-frontend#100] opened 2023-12-30 21:52 UTC
the `/user/{id}` page seems to show a general transaction overview instead of only the persons transactions.

**Comment by CodeNamedRobin** [comment] 2023-12-30 21:53
Duplicate of #96

**Comment by rinkp** [comment] 2023-12-30 22:00
So it is not completed?

**Comment by CodeNamedRobin** [comment] 2023-12-30 22:25
Fine, duplicate of #96

**Comment by CodeNamedRobin** [comment] 2023-12-30 22:26
Fine, duplicate of #96

**Closed as not planned by CodeNamedRobin** 2023-12-30 22:26 UTC
