### ISSUE TITLE
Form validation is always in English

### ISSUE THREAD

**Issue by tomudding** [GEWIS/sudosos-frontend#174] opened 2024-05-20 13:22 UTC
All standard form validation error messages are in English even when having the interface in Dutch:
![image](https://github.com/GEWIS/sudosos-frontend-vue3/assets/4983571/e2db3dc8-3b11-452f-9c37-1b95e83e8b99)

Also applies to a custom string: https://github.com/GEWIS/sudosos-frontend-vue3/blob/cdc992f776cfd434833b2829d2feb1f90b4f2f5d/src/components/BalanceWithTopupComponent.vue#L64

**Comment by SuperVK** [comment] 2024-05-20 15:45
Duplicate of #158

**Closed as completed by SuperVK** 2024-05-20 15:45 UTC
